run_parking_inventory_preprocess: False
run_parking_spaces_estimation: False
run_ABM_preprocess: True


#parking inventory preprocess settings
raw_parking_inventory: T:\ABM\data\sr15_inputs\landuse_prep\parking_inputs\mgra_parking_inventory.csv

#parking space estimation settings
base_lu: T:\socioec\Current_Projects\SR15\S0\version16\abm_csv\mgra15_based_input_2022.csv
bike_net: T:\ABM\data\sr15_inputs\landuse_prep\parking_inputs\SANDAG_Bike_Net.shp
bike_node: T:\ABM\data\sr15_inputs\landuse_prep\parking_inputs\SANDAG_Bike_Node.shp
geometry_file: T:\ABM\data\sr15_inputs\landuse_prep\parking_inputs\mgra15.shp

#parking cost estimation settings
# Files for parking policies
implement_policy: True
policy_type: 'mohubs' #possible values: 'pca' for PCA MGRAs,' mohubs' for ALL Mobility Hubs
parking_policy: "parking_outputs/ParkingPolicies_${scenario_year}.csv" #only 2035 present
update_rate: 1 #possible values: 1,1.5,0.5

#ABM preprocessing settings
input_dir: T:\ABM\data\sr15_inputs\landuse_prep
EF_dir: T:\socioec\Current_Projects\SR15\S0\version16\abm_csv
output_dir: .\
scenario_year: 2035
ff_year: 2035  #Flexible fleet year
households_file: synthetic_households_${scenario_year}.csv
persons_file: synthetic_persons_${scenario_year}.csv
landuse_file: mgra15_based_input_${scenario_year}.csv
auxiliary_file: auxiliary.csv #School and AV data
micro_mob_file: micro_mobility.csv

imputed_parking_df: imputed_parking_costs.csv
street_file : aggregated_street_data.csv
model_params_free: free_spaces_ols_params.csv #_version number for EF directory
model_params_paid: paid_spaces_ols_params.csv

# Parameters
walk_dist: 0.5 #in miles #0.5 default #0.25 for all Mohubs
walk_coef: -0.3
max_est_paid_spaces: 3000
max_est_free_spaces: 1000

#common settings
parking_output_dir: T:\ABM\user\sxu\ABM3\land_use_prep\0822\parking_outputs

#SQL Server Connection
server : 'DGISWSQL22'
database : 'RP2025'