channels:
  - defaults
dependencies:
  - pip
  - folium
  - geopandas
  - matplotlib
  - networkx
  - numpy
  - scipy
  - seaborn
  - scikit-learn
  - sqlalchemy
  - statsmodels
  - tqdm
  - pyyaml
  - pip:
    - geonetworkx
    - osmnx
    - alphashape