space_estimation_method: 'lm'
output_dir: "T:/ABM/data/sr15_inputs/landuse_prep/parking_inputs"

# Inputs
inputs:
  land_use: "T:/socioec/Current_Projects/SR15/S0/version7/abm_csv/mgra15_based_input_2022_01.csv"       
  #To be changed for different years
  geometry: "T:/ABM/data/sr15_inputs/landuse_prep/parking_inputs/mgra15.shp"
  raw_parking_inventory: "T:/ABM/data/sr15_inputs/landuse_prep/parking_inputs/mgra_parking_inventory.csv"

outputs:
  combined_df: 'T:/ABM/data/sr15_inputs/landuse_prep/final_parking_data_2022.csv'           
  #To be changed for different years

output_columns: 
  combined_df: 
    mgra:
    exp_hourly:
    exp_daily:
    exp_monthly:
    parking_type:
    spaces: parking_spaces

# Parameters
walk_dist: 0.5
walk_coef: -0.3