# Input settings
input:
  input_dir: 'inputs'
  random_seed: 42
  filenames:
    households: 'households.csv'
    persons: 'persons.csv'
    mgra_xwalk: 'xref_mgra13-15.csv'
    taz_xwalk: 'xref_taz13_15.csv'
    land_use: 'mgra13_based_input2035.csv'
    land_use_abm3: 'mgra15_based_input2035.csv'
    input_s15_per: 'input_s15_persons.csv'
    parking_cost_s14: 'mgraParkingCost.csv'
    mgra_s14_shp: 'shapefiles/SANDAG_MGRA.shp'
    mgra_s15_shp: 'shapefiles/mgra15.shp'

# Output settings
output:
  output_dir: '/outputs'
  filenames:
    households: 'households.csv'
    persons: 'persons.csv'
    land_use: 'mgra15_based_input2035.csv'