space_estimation_method: 'lm'
cache_dir: "./output/cache"
output_dir: "./output/parking"
plots_dir: "./output/plots"

# Inputs
inputs:
  land_use: "T:/socioec/Current_Projects/SR15/S0/version9/abm_csv/mgra15_based_input_2035.csv"       #To be changed for different years
  geometry: "T:/ABM/data/sr15_inputs/landuse_prep/parking_inputs/mgra15.shp"
  raw_parking_inventory: "T:/ABM/data/sr15_inputs/landuse_prep/parking_inputs/mgra_parking_inventory.csv"

outputs:
  combined_df: 'T:/ABM/data/sr15_inputs/landuse_prep/final_parking_data_2035.csv'           #To be changed for different years

output_columns: 
  combined_df: 
    mgra:
    exp_hourly:
    exp_daily:
    exp_monthly:
    parking_type:
    spaces: parking_spaces

# Parameters
walk_dist: 0.5
walk_coef: -0.3

# Which models to run, comment out any that you wish to not run. 
# However, be sure that the input is ready for whatever the new first model is.
# For example, if you have parking data cleaned up already, it can be fed into the 'create_districts' model.
# Or if you manually estimated spaces, you can skip that model too.
models:
  - run_reduction
  - run_imputation
  - create_districts
  - run_space_estimation
  - run_expected_parking_cost
  - write_output