input_dir: T:\ABM\data\sr15_inputs\landuse_prep
EF_dir: T:\socioec\Current_Projects\SR15\S0\version16\abm_csv #T:\socioec\Current_Projects\SR15\S0\version8\abm_csv
output_dir: .\
scenario_year: 2035

households_file: synthetic_households_${scenario_year}.csv
persons_file: synthetic_persons_${scenario_year}.csv
landuse_file: mgra15_based_input_${scenario_year}.csv


auxiliary_file: auxiliary.csv #School and AV data
#parking_file: final_parking_data_2035_v11.csv #final_parking_data_${scenario_year}.csv
micro_mob_file: micro_mobility.csv
hubs_mapping: mobilityHubMGRAs.csv
microtransit_file: microtransit_2035.yaml

# Parameters
walk_dist: 0.5 #in miles
walk_coef: -0.3
space_estimation_method: 'lm'

geometry: "parking_inputs/mgra15.shp"
imputed_parking_df: "parking_outputs/imputed_parking_costs.csv"
street_file : "parking_outputs/aggregated_street_data.csv"
model_params: "parking_outputs/ols_params.csv"
# Delete files from input for new street data and ols parameters

# Files for parking policies
implement_policy: True
mgra_moHub_map: "parking_outputs/moHub_mgra.csv"
parking_policy: "parking_outputs/ParkingPolicies.csv"
update_rate: 1 #possible values: 1,1.5,0.5