input_dir: T:\ABM\data\sr15_inputs\landuse_prep
EF_dir: T:\socioec\Current_Projects\SR15\S0\version16\abm_csv #T:\socioec\Current_Projects\SR15\S0\version8\abm_csv
output_dir: .\
scenario_year: 2035

households_file: synthetic_households_${scenario_year}.csv
persons_file: synthetic_persons_${scenario_year}.csv
landuse_file: mgra15_based_input_${scenario_year}.csv


auxiliary_file: auxiliary.csv #School and AV data
micro_mob_file: micro_mobility.csv
mgra_moHub_map: "moHub_mgra_map.csv"
microtransit_file: microtransit_2035.yaml

# Parameters
walk_dist: 0.5 #in miles
walk_coef: -0.3
space_estimation_method: 'lm'

geometry_file: "parking_inputs/mgra15.shp"
imputed_parking_df: "parking_outputs/imputed_parking_costs.csv"
street_file : "parking_outputs/aggregated_street_data.csv"
model_params_free: "parking_outputs/free_spaces_ols_params.csv" #_version number for EF directory
model_params_paid: "parking_outputs/paid_spaces_ols_params.csv"
# Comment files from input for new street data and ols parameters

# Files for parking policies
implement_policy: False
policy_type: 'mohubs' #possible values: 'pca' for PCA MGRAs,' mohubs' for ALL Mobility Hubs
parking_policy: "parking_outputs/ParkingPolicies_${scenario_year}.csv"
update_rate: 1 #possible values: 1,1.5,0.5